### PR TITLE
Proxy partials

### PR DESCRIPTION
**Pull request by marinintim**

### CODE REVIEW

**Comment by marinintim** [comment]
Somehow it corrupts partials object, so on second and subsequent renders partials object filled not with filename, but with filename contents

**Comment by coderhaoxin** [comment]
@marinintim can you add a test for this? :smile:

**Comment by marinintim** [comment]
@coderhaoxin added! But in Hogan, not sure if Jade has partials.
:ship:

**Comment by coderhaoxin** [comment]
@marinintim land 9cdf9fd29d599bf10f5deda0a4806cb2bcf12a33

co-views@1.0.0

**Pull request closed without merging**
